env:
    BUILD_HOSTNAME: "nfs-project"
    rcloneconfig: "ENCRYPTED[8bba78e2d6cba57a09a1077fd890dd9896da6e24278b8ff19f5c83b99a4054e7fea40bab5b39728acf306634acaad136]"
    TG_TOKEN: "ENCRYPTED[5889643df6c5e52e896de965d5d3f6224a81ad43acf01cfd1f1c552ceb663f5b368697ec679e0b8c7841f9042dc4e08c]"
    TG_CHAT_ID: "ENCRYPTED[ea74b5030a1f5738ef3c505ed891a207b00d8a371d34055998510dbf33b48f31c4aaabc0fc129f7ccebf0366df89dd7e]"
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /home/cirrus-ci-build
    BUILD_CCACHE_ONLY: "true" #true or false
    device: rosy
    LUNCH: evolution_rosy-userdebug
    BUILD_TYPE: mka evolution
    name_rom: $(grep init $CIRRUS_WORKING_DIR/sync.sh -m 1 | cut -d / -f 4)
    
task:
  name: Test Build Rom
  timeout_in: 120m
  container:
    image: anggit86/docker:cirrus
    cpu: 8
    memory: 32G
    volumes:
          - /home/cirrus-ci-build/rom:/home/cirrus-ci-build/rom
          - /home/cirrus-ci-build/ccache:/home/cirrus-ci-build/ccache
  
  Load_script:
     - ./load.sh
  Environment_script:
     - cat /etc/os* && env && nproc && gcc --version && clang --version
  Storage-Check_script:
     - df -h && lsblk && ls -l -a -h
  Sync_rom_script:
     - set -exv
     - mkdir -p $CIRRUS_WORKING_DIR/rom/$name_rom
     - cd $CIRRUS_WORKING_DIR/rom/$name_rom
     - rm -rf .repo/local_manifests
     - command=$(head $CIRRUS_WORKING_DIR/sync.sh -n $(expr $(grep 'build/envsetup.sh' $CIRRUS_WORKING_DIR/sync.sh -n | cut -f1 -d:) - 1))
     - bash -c "$command" || true
  Build_rom_script:
     - ./build.sh
  Upload_build_script:
     - ./ziping.sh