env:
    rcloneconfig: "ENCRYPTED[6b6367eb0b1a215a793716317221b73a3b7041e63ba6df999bd3220fa6ec355697c47380808584851da4b158e0392d30]"
    TG_TOKEN: "ENCRYPTED[5889643df6c5e52e896de965d5d3f6224a81ad43acf01cfd1f1c552ceb663f5b368697ec679e0b8c7841f9042dc4e08c]"
    TG_CHAT_ID: "ENCRYPTED[ea74b5030a1f5738ef3c505ed891a207b00d8a371d34055998510dbf33b48f31c4aaabc0fc129f7ccebf0366df89dd7e]"
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp"
    
task:
  name: Test
  timeout_in: 2m
  container:
      image: anggit86/dev:latest
      cpu: 2
      memory: 4G

  env_script:
    - env

task:
  name: Build
  depends_on:
    - Test
  timeout_in: 4h
  container:
      image: anggit86/dev:latest
      cpu: 24
      memory: 120G
        
  Build-Env-Setup_background_script:
       - ./env.sh

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - ./sync.sh

  Build_script:
#      - ./collect.sh
      - ./final.sh

#  Upload_script:
#      - ./ziping.sh
#      - ./upload_rom.sh      
